doctors_list = {
    "Dr. A Sandhya Kishore": "images/ASandhyaKishore.jpg",
    "Dr. A. Chandra Rekha": "images/AChandraRekha.jpg",
    "Dr. A. Manasa": "images/AManasa.jpg",
    "Dr. Abdul D Khan": "images/AbdulDKhan.jpg",
    "Dr. Allaka Kishore Kumar": "images/AllakaKishoreKumar.jpg",
    "Dr. Anil Dev Dutt V": "images/AnilDevDuttV.jpg",
    "Dr. Boddepalli Sateesh Babu": "images/BoddepalliSateeshBabu.jpg",
    "Dr. Chandra Keerthana": "images/ChandraKeerthana.jpg",
    "Dr. D V R Raju": "images/DVRRaju.jpg",
    "Dr. Earle Santosh Kumar": "images/EarleSantoshKumar.jpg",
    "Dr. Girish Karri": "images/GirishKarri.jpg",
    "Dr. Harshavardhan K": "images/DHarshavardhanK.jpg",
    "Dr. K Satya Varaprasad": "images/KSatyaVaraprasad.jpg",
    "Dr. Konagala Ravi Kumar": "images/KonagalaRaviKumar.jpg",
    "Dr. Lam Amith": "images/LamAmith.jpg",
    "Dr. M Shiva Prasad": "images/MShivaPrasad.jpg",
    "Dr. Madhumalini Sharma": "images/MadhumaliniSharma.jpg",
    "Dr. Manasa Ram": "images/ManasaRam.jpg",
    "Dr. Manchala Ramesh Kumar": "images/ManchalaRameshKumar.jpg",
    "Dr. Manikante Vijaya Vani": "images/ManikanteVijayaVani.jpg",
    "Dr. Manohar Varma": "images/ManoharVarma.jpg",
    "Dr. Mettu Jyothsna": "images/MettuJyothsna.jpg",
    "Dr. Mokkapati Mounika": "images/MokkapatiMounika.jpg",
    "Dr. N Satish Varma": "images/NSatishVarma.jpg",
    "Dr. Nagapushyami. G": "images/NagapushyamiG.jpg",
    "Dr. Naveen Kumar Anem": "images/NaveenKumarAnem.jpg",
    "Dr. Navya Sahithi": "images/NavyaSahithi.jpg",
    "Dr. P. Pavan Kumar": "images/PPavanKumar.jpg",
    "Dr. P.Latha": "images/PLatha.jpg",
    "Dr. Praveena Sreerama": "images/PraveenaSreerama.jpg",
    "Dr. Radhika Potluri": "images/RadhikaPotluri.jpg",
    "Dr. Ramanand Satapathy": "images/RamanandSatapathy.jpg",
    "Dr. Ravi Kumar B": "images/DRaviKumarB.jpg",
    "Dr. Sajani": "images/Sajani.jpg",
    "Dr. Sandeep Maheswara Reddy Kallam": "images/SandeepMaheswaraReddyKallam.jpg",
    "Dr. Satish Anne": "images/SatishAnne.jpg",
    "Dr. Sesha Mohan Debta": "images/SeshaMohanDebta.jpg",
    "Dr. Sireesha Anne": "images/SireeshaAnne.jpg",
    "Dr. Siva Rama Raju": "images/SivaRamaRaju.jpg",
    "Dr. Sivaji Kavuri": "images/SivajiKavuri.jpg",
    "Dr. Sravanthi Alluri": "images/SravanthiAlluri.jpg",
    "Dr. Sriharsha Badana": "images/SriharshaBadana.jpg",
    "Dr. Srinivas Manohar": "images/SrinivasManohar.jpg",
    "Dr. Sunil Talasila": "images/SunilTalasila.jpg",
    "Dr. Supriya Satapathy": "images/SupriyaSatapathy.jpg",
    "Dr. Swetha Naidu Karaka": "images/SwethaNaiduKaraka.jpg",
    "Dr. T Kiran Kumar": "images/TKiranKumar.jpg",
    "Dr. Ujwala Talasila": "images/UjwalaTalasila.jpg",
    "Dr. V V K Vidyakar": "images/VVKVidyakar.jpg",
    "Dr. Teja Vinod": "images/TejaVinod.jpg",

}